server:
  port: 8080 # ??????? 8080 ??

spring:
  datasource:
    # 1. ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 2. ????? (???kfc_ordering ?????????????)
    url: jdbc:mysql://localhost:3306/kfc_ordering?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    # 3. ?? (??? root)
    username: root
    # 4. ?? (!!! ?????????? MySQL ??? !!!)
    password: 123456

# MyBatis-Plus ?? (?????? SQL ???????)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl